title: Xinlin Wang's Homepage
page-top-title: Xinlin Wang
top-section-bg-text: Computer science and its Application
home-subtitle: 王欣霖&ensp;|&ensp;Xinlin Wang
copyright-text: '&copy; Xinlin Wang Post in 2025.'
